version: "3.9"
services:
  mongo:
    container_name: mongo
    image: registry.cn-shenzhen.aliyuncs.com/apsubox/mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: apsu
      MONGO_INITDB_ROOT_PASSWORD: yangpaopao
    ports:
      - "27017:27017"
    volumes:
      - ./volume/mongo/:/data/db/
  mosquitto:
    container_name: mosquitto
    # build: ./mosquitto/.
    image: registry.cn-shenzhen.aliyuncs.com/apsubox/mosquitto
    restart: unless-stopped
    environment:
    - TZ=Asia/Shanghai
    - APSU_EDGE_TOKEN=${APSU_EDGE_TOKEN}
    - BID=${BID}
    - BPWD=${BPWD}
    ports:
    - "1883:1883"
    - "9001:9001"
    - "8883:8883"
    - "9883:9883" 
    volumes:
    - ./volume/mosquitto/data:/mosquitto/data
    - ./volume/mosquitto/logs:/mosquitto/logs
    - ./volume/mosquitto/pwfile:/mosquitto/pwfile
  boxserver:
      container_name: boxserver
      image: registry.cn-shenzhen.aliyuncs.com/apsubox/boxserver
      # build: ./server/.
      restart: unless-stopped
      ports:
      - "4000:4000"
      environment:
        - APSU_EDGE_TOKEN=${APSU_EDGE_TOKEN}
        - BID=${BID}
        - BPWD=${BPWD}
        - CID=${CID}
        - Btoken=${Btoken}
        - PORT=4000
        - REMOTE_HOST=https://www.kknd.cn/graphql
        - MQTT_URL=http://mosquitto
        - INFLUXDB_URL=http://influxdb:8086
        - DB_URL=mongodb://apsu:yangpaopao@mongo/box?authSource=admin&w=majority&readPreference=nearest
      volumes:
      - /etc/environment:/usr/src/app/environment
      depends_on: 
      - mongo
      - mosquitto
      - influxdb
  boxweb:
      container_name: web
      image: registry.cn-shenzhen.aliyuncs.com/apsubox/boxweb
      # build: ./web/.
      restart: unless-stopped
      ports:
      - "80:3000"
      environment:
      - NEXT_PUBLIC_SERVER_URL=http://boxserver:4000/graphql
      - NEXT_PUBLIC_MQTT_SERVER=http://mosquitto
      depends_on: 
      - boxserver
  influxdb:
      container_name: influxdb
      image: "registry.cn-shenzhen.aliyuncs.com/apsubox/influxdb"
      restart: unless-stopped
      ports:
      - "8086:8086"
      environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=apsu
      - DOCKER_INFLUXDB_INIT_PASSWORD=yangpaopao
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=asfaskjsadfjklasdjf
      volumes:
      - ./volume/influxdb/data:/var/lib/influxdb2 
      - ./volume/influxdb/config:/etc/influxdb2
  red:
      container_name: red
      image: registry.cn-shenzhen.aliyuncs.com/apsubox/red
      restart: unless-stopped
      user: "0"
      environment:
      - TZ=Asia/Shanghai
      ports:
      - "1880:1880"
      volumes:
      - ./volume/red/data:/data
      - ./volume/red/ssh:/root/.ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/vcio:/dev/vcio"
      - "/dev/gpiomem:/dev/gpiomem"
  portainer:
      container_name: portainer
      image: registry.cn-shenzhen.aliyuncs.com/apsubox/portainer
      restart: unless-stopped
      ports:
      - "8000:8000"
      - "9000:9000"
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volume/portainer-ce/data:/data
  grafana:
      container_name: grafana
      image: registry.cn-shenzhen.aliyuncs.com/apsubox/grafana
      restart: unless-stopped
      user: "0"
      ports:
      - "3000:3000"
      environment:
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      volumes:
      - ./volume/grafana/data:/var/lib/grafana
      - ./volume/grafana/log:/var/log/grafana
