version: '3.6'
services:
  boxserver:
    container_name: boxserver
    image: registry.cn-shenzhen.aliyuncs.com/apsu/boxserver
    # build: ./build/server/.
    restart: unless-stopped
    ports:
    - "4000:4000"
    environment:
      - APSU_EDGE_TOKEN=${APSU_EDGE_TOKEN}
      - PORT=4000
      - REMOTE_HOST=https://www.kknd.cn/graphql
      - LOCAL_MQTT=mosquitto
    volumes:
    - ./volume/boxserver/data:/usr/src/app/data
  boxweb:
    container_name: boxweb
    image: registry.cn-shenzhen.aliyuncs.com/apsu/boxweb
    # build: ./build/web/.
    restart: unless-stopped
    ports:
    - "80:3000"
    environment:
      - NEXT_PUBLIC_API_ADDRESS=http://boxserver:4000/api
    volumes:
    - ./volume/boxweb/data:/usr/src/app/dat
  red:
    container_name: red
    image: registry.cn-shenzhen.aliyuncs.com/apsu/red
    # build: ./build/red/.
    restart: unless-stopped
    user: "0"
    environment:
    - TZ=Asia/Shanghai
    ports:
    - "1880:1880"
    volumes:
    - ./volume/red/data:/data
    - ./volume/red/ssh:/root/.ssh
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
    devices:
    - "/dev/ttyAMA0:/dev/ttyAMA0"
    - "/dev/vcio:/dev/vcio"
    - "/dev/gpiomem:/dev/gpiomem"
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    environment:
    - TZ=Asia/Shanghai
    ports:
    - "1883:1883"
    - "9001:9001"
    - "8883:8883"
    - "9883:9883" 
    volumes:
    - ./config/mosquitto/config:/mosquitto/config
    - ./config/mosquitto/certs:/mosquitto/certs
    - ./volume/mosquitto/data:/mosquitto/data
    - ./volume/mosquitto/logs:/mosquitto/logs
    - ./volume/mosquitto/pwfile:/mosquitto/pwfile
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    ports:
    - "8000:8000"
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./volume/portainer-ce/data:/data
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: "0"
    ports:
    - "3000:3000"
    environment:
    - GF_PATHS_DATA=/var/lib/grafana
    - GF_PATHS_LOGS=/var/log/grafana
    volumes:
    - ./volume/grafana/data:/var/lib/grafana
    - ./volume/grafana/log:/var/log/grafana
  influxdb:
    container_name: influxdb
    image: arm32v7/influxdb:latest
    restart: unless-stopped
    ports:
    - "8086:8086"
    environment:
    - DOCKER_INFLUXDB_INIT_MODE=setup
    - DOCKER_INFLUXDB_INIT_USERNAME=apsu
    - DOCKER_INFLUXDB_INIT_PASSWORD=yangpaopao
    - DOCKER_INFLUXDB_INIT_ORG=my-org
    - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=asfaskjsadfjklasdjf
    volumes:
    - ./volume/influxdb/data:/var/lib/influxdb2 
    - ./volume/influxdb/config:/etc/influxdb2

